### ISSUE TITLE
Script engine may print logging information when it is initialized

### ISSUE THREAD

**Issue by laurentpellegrino** [tobwiens/jsr223-docker-compose#11]
By default, especially if docker-compose is not installed in the expected destination folder, the script engine prints logging information such as the one below when it is initialized:

```
2015-11-18 18:16:22.0045 WARN main jsr223.docker.compose.utils.DockerComposeUtilities - Failed to retrieve docker compose version.
```

Unfortunately, some tests related to Scheduling project are written assuming that task output is not polluted by messages which are not produced by the task itself. Consequently, [some tests are currently failling](http://jenkins.activeeon.com/job/scheduling/jdk=JDK8,label=Linux/168/testReport/junit/functionaltests.credentials/TestThirdPartyCredentialsDefined/testThatCredentialsAreCreatedIfThirdPartyCredentialHaveBeenDefined/)

Besides, script enginew are loaded by scripts such `proactive-client`. In that case, a disrupting message is displayed when the script is used in non-interactive mode:

```
lpellegr@oops:scheduling$ ./bin/proactive-client 
2015-11-18 18:29:28.0948 WARN main jsr223.docker.compose.utils.DockerComposeUtilities - Failed to retrieve docker compose version.
Type help() for interactive help 
> 
```

A simple solution is to avoid to write something on the standard output in the initialization method of the script engine. Logger output related to initialization could be saved for instance in a file and the content of this file forwarded to standard output only when a docker-compose script is evaluated.

**Comment by tobwiens** [comment]
The script engine tries to retrieve the docker-compose version when the script engines are initialized, which is at each start of any task. I can remove that functionality and hide the docker-compose version from ProActive. I'd like to prevent it failing silently, that's why I'd like to remove it.
